arm64_task:
  arm_macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - echo "Hello World from macOS!"
    - arch

x86_64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - echo "Hello World from macOS!"
    - arch
